name: talentspotfilmmaker
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  cached_network_image: ^3.4.1
  file_picker: ^9.2.0
  fl_chart: ^0.70.2
  flutter:
    sdk: flutter
  flutter_cached_pdfview: ^0.4.3
  flutter_pdfview: ^1.4.0+1
  flutter_svg: ^2.0.17
  google_fonts: ^6.2.1
  image_picker: ^1.1.2
  intl: ^0.20.2
  supabase_flutter: ^2.8.4
  timeago: ^3.2.2
  video_player: ^2.9.3
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
