name: talentspot
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  cached_network_image: ^3.4.1
  confetti: ^0.8.0
  file_picker: ^9.2.1
  flutter:
    sdk: flutter
  flutter_credit_card: ^4.1.0
  google_fonts: ^6.2.1
  image_picker: ^1.1.2
  intl: ^0.20.2
  lottie: ^3.3.1
  supabase_flutter: ^2.8.4
  timeago: ^3.2.2
  universal_io: ^2.2.2
  video_player: ^2.9.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/